# Generated by Django 5.0.6 on 2024-06-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('learning_course_hours', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('learning_method', models.CharField(max_length=20)),
                ('course_what_about', models.CharField(max_length=20)),
                ('course_level', models.PositiveSmallIntegerField()),
                ('course_trainer', models.PositiveSmallIntegerField()),
                ('learning_material', models.PositiveSmallIntegerField()),
                ('course_assignment', models.PositiveSmallIntegerField()),
                ('course_student', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
