# Generated by Django 5.0.7 on 2024-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_what_about',
        ),
        migrations.AddField(
            model_name='course',
            name='course_about',
            field=models.CharField(default='default_course_about', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_material',
            field=models.CharField(max_length=20),
        ),
    ]
