# Generated by Django 5.0.6 on 2024-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('table', models.PositiveSmallIntegerField()),
                ('method_of_teaching', models.CharField(max_length=20)),
                ('information_of_student', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('chairs', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('class_assignment', models.PositiveSmallIntegerField()),
                ('learning_hours', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
