# Generated by Django 5.0.7 on 2024-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='capacity',
            new_name='class_numberof_student',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='information_of_student',
            new_name='class_prefect',
        ),
        migrations.AddField(
            model_name='class',
            name='trainer',
            field=models.CharField(default='default_trainer', max_length=100),
        ),
    ]
