# Generated by Django 5.0.7 on 2024-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='code',
            new_name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.CharField(default='default_enrollment_year', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(default='default_hobby', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_bio',
            field=models.TextField(default='default_student_bio'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
